// 테스트용 가짜 Supabase — 실제 DB 규칙(RPC)을 간단히 흉내냄
const uid = () => 'u' + Math.random().toString(36).slice(2, 11);
const now = () => new Date().toISOString();
const DB = window.__DB = { pricing: [], events: [], push_subs: [], profiles: [], companies: [], stores: [], members: [], shift_templates: [], shift_overrides: [], daily_reports: [], expenses: [], incentives: [], job_posts: [], job_slots: [], applications: [], ticket_ledger: [], wallet_ledger: [], notifications: [], inquiries: [], used_items: [], transfer_leads: [], attendance: [], join_requests: [], store_metrics: [], store_quests: [], stock: [], orders: [], store_rotation: [], purchases: [], lesson_progress: [], quiz_results: [], withdrawals: [], course_interest: [], payments: [], company_quiz: [], notices: [], franchise_postings: [], franchise_events: [], franchise_leads: [], transfer_listings: [{ id: 'tl1', area: '서울 마포구', pyeong: 55, tables: 8, deposit: 5e7, rent: 48e5, premium: 22e7, monthly_sales: 68e6, monthly_profit: 195e5, sales_hist: [61e6, 64e6, 66e6, 63e6, 69e6, 68e6], verified: true, premium_ad: true, headline: '홍대 대형 홀덤펍', body: '인수인계 가능', status: 'open', created_at: new Date().toISOString() }], __storage: [], store_goals: [], store_fixed: [], day_opens: [], products: [{ id: 1, cat: 'drink', name: '캔 콜라 245ml', unit: '30캔', price: 21000, sale_price: 18900, body: '테스트', active: true, sort: 1 }, { id: 2, cat: 'drink', name: '캔 사이다 245ml', unit: '30캔', price: 20000, sale_price: 17900, active: true, sort: 2 }, { id: 8, cat: 'snack', name: '감자칩 대용량', unit: '12봉', price: 28000, sale_price: 24500, active: true, sort: 8 }, { id: 11, cat: 'supply', name: '플라스틱 카드 12덱', unit: '1박스', price: 186000, sale_price: 149000, active: true, sort: 11 }] };
const PK = { company_quiz: ['company_id'], shift_templates: ['member_id', 'weekday'], shift_overrides: ['member_id', 'work_date'], daily_reports: ['store_id', 'report_date'], store_quests: ['store_id', 'month', 'key'], stock: ['store_id', 'item_id'], store_goals: ['store_id', 'month'], store_fixed: ['store_id', 'month'], day_opens: ['store_id', 'day'], products: ['id'], store_rotation: ['store_id'], lesson_progress: ['user_id', 'lesson'], sched_rounds: ['store_id', 'month'], sched_avail: ['member_id', 'month'] };
let user = null; const cbs = []; window.__USERS = window.__USERS || {};
const me = () => { if (!user) throw { message: '로그인이 필요해요' }; return user.id; };
const noti = (u, body) => u && DB.notifications.push({ id: DB.notifications.length + 1, user_id: u, body, read: false, created_at: now() });
const managers = st => { const s = DB.stores.find(x => x.id === st); return DB.members.filter(m => m.company_id === s.company_id && m.user_id && (m.role === 'owner' || (m.role === 'manager' && m.store_id === st))).map(m => m.user_id); };
const canManage = st => managers(st).includes(user?.id);
const tickets = u => DB.ticket_ledger.filter(x => x.user_id === u).reduce((a, x) => a + x.delta, 0);
const OWNED = { notifications: 'user_id', inquiries: 'from_user', lesson_progress: 'user_id', quiz_results: 'user_id', course_interest: 'user_id' };
const TODAY0 = () => new Date().toISOString().slice(0, 10);
const compActive = co => !!co && ((co.plan === 'pro' && co.paid_until && new Date(co.paid_until) > new Date()) || (co.trial_ends && co.trial_ends >= TODAY0()) || (co.diag_until && new Date(co.diag_until) > new Date()));
function builder(t) {
  let op = 'select', payload = null, filters = [], single = false, order = null, lim = 0;
  const b = { select() { return b }, eq(k, v) { filters.push(r => r[k] === v); return b }, neq(k, v) { filters.push(r => r[k] !== v); return b }, in(k, v) { filters.push(r => v.includes(r[k])); return b }, gte(k, v) { filters.push(r => r[k] >= v); return b }, lte(k, v) { filters.push(r => r[k] <= v); return b }, like(k, v) { const re = new RegExp('^' + v.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/%/g, '.*') + '$'); filters.push(r => re.test(r[k] || '')); return b },
    order(k, o) { order = [k, o?.ascending !== false]; return b }, limit(n) { lim = n; return b }, maybeSingle() { single = true; return b },
    insert(p) { op = 'insert'; payload = p; return b }, update(p) { op = 'update'; payload = p; return b }, upsert(p) { op = 'upsert'; payload = p; return b }, delete() { op = 'delete'; return b },
    then(res, rej) { try { res(run()) } catch (e) { res({ data: null, error: e }) } } };
  function run() {
    const T = t === 'franchise_public' ? DB.franchise_postings.filter(r => r.status === 'active') : DB[t]; if (!T) return { data: single ? null : [], error: null }; const match = r => filters.every(f => f(r));
    if (['insert', 'upsert'].includes(op) && ['daily_reports', 'expenses', 'shift_templates', 'shift_overrides', 'members'].includes(t)) { const r0 = [].concat(payload)[0] || {}; const sid = r0.store_id || DB.members.find(m => m.id === r0.member_id)?.store_id; const co = DB.companies.find(c => c.id === (r0.company_id || DB.stores.find(x => x.id === sid)?.company_id)); if (co && !compActive(co) && !DB.profiles.find(p => p.id === user?.id)?.is_hq) throw { message: '무료 체험이 끝났어요. 프로로 계속 쓰면 바로 이어서 입력할 수 있어요' }; }
    if (op === 'insert') { const ins = []; [].concat(payload).forEach(p => { const row = { id: uid(), active: true, created_at: now(), ...p }; if (t === 'franchise_postings') Object.assign(row, { owner_user: me(), status: 'draft', monthly_fee: 300000 }); if (t === 'orders') { row.status = row.status || '접수'; DB.profiles.filter(x => x.is_hq).forEach(h => noti(h.id, '새 발주 요청')); } if (t === 'stores') Object.assign(row, { join_code: 'D-' + uid().slice(1, 7).toUpperCase(), need_by_wd: [3, 4, 3, 4, 6, 7, 2], night_start: '22:00:00', night_end: '06:00:00' }); T.push(row); ins.push(row); }); return { data: single ? ins[0] : ins, error: null } }
    if (op === 'update') { T.filter(match).forEach(r => { Object.assign(r, payload); if (t === 'used_items' && r.status === '판매완료') { r.boost = null; r.boost_until = null; } if (t === 'inquiries' && payload.reply) noti(r.from_user, '운영사가 문의에 답변했어요'); }); return { data: null, error: null } }
    if (op === 'delete') { for (let i = T.length - 1; i >= 0; i--)if (match(T[i])) T.splice(i, 1); return { data: null, error: null } }
    if (op === 'upsert') { const k = PK[t]; for (const pl of [].concat(payload)) { if (t === 'day_opens' && !pl.opened_at) pl.opened_at = now(); const ex = T.find(r => k.every(c => r[c] === pl[c])); ex ? Object.assign(ex, pl) : T.push({ ...pl }); } return { data: null, error: null } }
    let out = T.filter(match).filter(r => !OWNED[t] || (t === 'inquiries' && DB.profiles.find(p => p.id === user?.id)?.is_hq) || r[OWNED[t]] === user?.id).map(r => ({ ...r }));
    if (t === 'attendance') out = out.filter(a => DB.members.find(m => m.id === a.member_id)?.user_id === user?.id);
    if (order) out.sort((a, b) => (a[order[0]] > b[order[0]] ? 1 : -1) * (order[1] ? 1 : -1)); if (lim) out = out.slice(0, lim);
    return { data: single ? (out[0] || null) : out, error: null };
  }
  return b;
}
const code = (st) => String(Math.floor(Date.now() / 30000) * 7919 % 1000000).padStart(6, '0') ;

const postFee = id => { const p = DB.job_posts.find(x => x.id === id), tp = DB.job_slots.filter(x => x.post_id === id).reduce((a, x) => a + x.pay, 0);
  if (p.kind === 'urgent') return tp + 10000 + DB.job_slots.filter(x => x.post_id === id).reduce((a, x) => a + Math.floor(x.pay * .05 / 10) * 10, 0) + (p.flash ? 3300 : 0);
  const j = p.top ? 12000 : { 2: 3000, 5: 5000, 8: 7000 }[p.jump_per_day] || 0, d = p.ad_days, disc = d >= 30 ? .2 : d >= 15 ? .15 : d >= 7 ? .1 : 0;
  return base(d) + Math.round((j + (p.flash ? 3300 : 0)) * d * (1 - disc) / 100) * 100; };
const base = d => d >= 30 ? 16500 : 8800;
const optFee = (top, jump, flash, d) => Math.round(((top ? 12000 : { 2: 3000, 5: 5000, 8: 7000 }[jump] || 0) + (flash ? 3300 : 0)) * d * (1 - (d >= 30 ? .2 : d >= 15 ? .15 : d >= 7 ? .1 : 0)) / 100) * 100;
const extraFee = (p, g) => g.days > 0 ? base(g.days) + optFee(g.top, g.jump, g.flash, g.days) : optFee(g.top && !p.top, g.jump > p.jump_per_day ? g.jump : 0, g.flash && !p.flash, Math.max(1, Math.ceil((new Date(p.expires_at || Date.now()) - Date.now()) / 864e5)));
const bizOk = v => { const d = String(v).replace(/\D/g, ''); if (d.length !== 10) return false; const w = [1, 3, 7, 1, 3, 7, 1, 3, 5]; const t = w.reduce((a, x, i) => a + x * +d[i], 0) + Math.floor(+d[8] * 5 / 10); return (10 - t % 10) % 10 === +d[9]; };
function fulfill(o) { const r = DB.payments.find(x => x.order_id === o); if (r.status === 'done') return { already: true, kind: r.kind }; r.status = 'done'; r.approved_at = now();
  if (r.kind === 'tickets') DB.ticket_ledger.push({ user_id: r.user_id, delta: [0, 1, 5, 10][r.arg.pack], reason: 'buy' });
  if (r.kind === 'pro') { const p = DB.profiles.find(x => x.id === r.user_id); p.pro_until = new Date(Date.now() + 30 * 864e5).toISOString(); DB.ticket_ledger.push({ user_id: r.user_id, delta: 2, reason: 'pro' }); }
  if (r.kind === 'academy') DB.companies.find(c => c.id === r.company_id).academy_at = now();
  if (r.kind === 'plan') Object.assign(DB.companies.find(c => c.id === r.company_id), { plan: r.arg?.plan === 'basic' ? 'basic' : 'pro', paid_until: new Date(Date.now() + 30 * 864e5).toISOString() });
  if (r.kind === 'post') { const p = DB.job_posts.find(x => x.id === r.arg.post); p.status = 'open'; p.expires_at = new Date(Date.now() + (p.kind === 'urgent' ? 1 : p.ad_days) * 864e5).toISOString(); }
  if (r.kind === 'post_extra') { const p = DB.job_posts.find(x => x.id === r.arg.post), g = r.arg; p.status = 'open'; p.expires_at = new Date(Math.max(Date.now(), new Date(p.expires_at || Date.now())) + (g.days || 0) * 864e5).toISOString(); p.ad_days += g.days || 0; p.top = p.top || !!g.top; p.jump_per_day = Math.max(p.jump_per_day || 0, g.jump || 0); p.flash = p.flash || !!g.flash; p.paid_amount = (p.paid_amount || 0) + r.amount; }
  if (r.kind === 'franchise') { const f = DB.franchise_postings.find(x => x.id === r.arg.post); f.status = 'active'; f.start_at = f.start_at || now(); f.end_at = new Date(Math.max(Date.now(), new Date(f.end_at || 0)) + 30 * 864e5).toISOString(); }
  if (r.kind === 'used_boost') { const u = DB.used_items.find(x => x.id === r.arg.item); u.boost = r.arg.type === 'urgent' ? 'urgent' : 'top'; u.boost_until = new Date(Date.now() + (r.arg.type === 'urgent' ? 7 : 3) * 864e5).toISOString(); }
  if (r.kind === 'diag') DB.companies.find(c => c.id === r.company_id).diag_until = new Date(Date.now() + 30 * 864e5).toISOString();
  if (r.kind === 'store') DB.stores.push({ id: uid(), company_id: r.company_id, name: r.arg.name, area: r.arg.area || null, need_by_wd: [3, 4, 3, 4, 6, 7, 2], join_code: 'X' + Math.random().toString(36).slice(2, 7).toUpperCase(), created_at: now(), holidays: [], fixed: {} });
  return { ok: true, kind: r.kind, amount: r.amount }; }
window.__autoPayMethod = 'CARD';
window.TossPayments = () => ({ payment: () => ({ requestPayment: async o => { window.__lastPay = o; setTimeout(() => window.__evPayReturn({ pay: 'ok', paymentKey: 'pk_test', orderId: o.orderId, amount: o.amount.value }), 30); } }) });
const RPC = window.__RPC = {
  sched_step: ({ p_store, p_month, p_status, p_deadline }) => { DB.sched_rounds = DB.sched_rounds || []; const r = DB.sched_rounds.find(x => x.store_id === p_store && x.month === p_month); if (r) { r.status = p_status; if (p_deadline) r.deadline = p_deadline; } else DB.sched_rounds.push({ store_id: p_store, month: p_month, status: p_status, deadline: p_deadline || null, short: [] }); if (p_status === 'sent') (DB.sched_avail || []).forEach(a => { a.confirm = null; a.confirm_note = null; }); return null; },
  create_company(a) { if (!/^\d{10}$/.test(String(a.p_biz_no).replace(/\D/g, ''))) throw { message: '사업자등록번호 10자리를 넣어주세요' }; const c = { id: uid(), name: a.p_name, brand: a.p_brand, biz_no: a.p_biz_no.replace(/\D/g, ''), biz_verified: bizOk(a.p_biz_no), plan: 'trial', trial_ends: new Date(Date.now() + 14 * 864e5).toISOString().slice(0, 10), created_at: now() }; DB.companies.push(c); DB.stores.push({ id: uid(), company_id: c.id, name: a.p_store, area: a.p_area, need_by_wd: [3, 4, 3, 4, 6, 7, 2], night_start: '22:00:00', night_end: '06:00:00', join_code: 'D-' + uid().slice(1, 7).toUpperCase(), created_at: now() }); DB.members.push({ id: uid(), company_id: c.id, store_id: null, user_id: me(), role: 'owner', nick: a.p_nick, active: true, created_at: now() }); DB.profiles.find(p => p.id === me()).kind = 'owner'; return c.id },
  start_dealer(a) { const p = DB.profiles.find(p => p.id === me()); Object.assign(p, { name: a.p_name, phone: a.p_phone, career_months: a.p_career, bio: a.p_bio, kind: p.kind || 'dealer' }); if (!DB.ticket_ledger.some(x => x.user_id === me() && x.reason === 'welcome')) DB.ticket_ledger.push({ user_id: me(), delta: 3, reason: 'welcome' }); },
  ticket_balance() { return tickets(me()) },
  create_post(a) { if (!canManage(a.p_store)) throw { message: '권한이 없어요' }; if (a.p_kind === 'urgent' && !['딜러', '플로어'].includes(a.p_role)) throw { message: '긴급 구인은 딜러·플로어만 돼요' }; const id = uid(); DB.job_posts.push({ id, store_id: a.p_store, kind: a.p_kind, job_role: a.p_role, title: a.p_title, body: a.p_body, pay_text: a.p_pay_text, work_time: a.p_work_time, heads: a.p_heads, taxi_amt: a.p_taxi, flash: a.p_flash, top: a.p_top, ad_days: a.p_days, jump_per_day: a.p_jump || 0, incentive: a.p_incentive || null, prefer: a.p_prefer || null, status: 'unpaid', expires_at: new Date(Date.now() + 864e5).toISOString(), created_at: now() }); (a.p_slots || []).forEach((x, i) => DB.job_slots.push({ id: uid(), post_id: id, idx: i + 1, start_t: x.start, end_t: x.end, pay: x.pay, extra: 0, status: 'OPEN', dealer_id: null })); return id },
  job_board() { me(); return DB.job_posts.filter(p => p.status === 'open').map(p => { const s = DB.stores.find(s => s.id === p.store_id); return { ...p, store_name: s.name, area: s.area, address: s.address, slots: DB.job_slots.filter(x => x.post_id === p.id).map(x => ({ start: x.start_t, end: x.end_t, pay: x.pay, status: x.status })) } }) },
  apply_job(a) { if (tickets(me()) < 1) throw { message: '지원권이 없어요' }; if (DB.applications.some(x => x.post_id === a.p_post && x.user_id === me())) throw { message: '이미 지원했어요' }; const id = uid(); DB.applications.push({ id, post_id: a.p_post, user_id: me(), status: 'applied', created_at: now() }); DB.ticket_ledger.push({ user_id: me(), delta: -1, reason: 'lock' }); managers(DB.job_posts.find(p => p.id === a.p_post).store_id).forEach(u => noti(u, '새 지원자가 있어요')); return id },
  my_applications() { return DB.applications.filter(x => x.user_id === me()).map(x => { const p = DB.job_posts.find(p => p.id === x.post_id); return { app_id: x.id, post_id: x.post_id, status: x.status, created_at: x.created_at, title: p.title, store_name: DB.stores.find(s => s.id === p.store_id).name, kind: p.kind } }) },
  post_applicants(a) { if (!canManage(DB.job_posts.find(p => p.id === a.p_post).store_id)) return []; return DB.applications.filter(x => x.post_id === a.p_post).map(x => { const pr = DB.profiles.find(p => p.id === x.user_id); return { app_id: x.id, name: pr.name, career_months: pr.career_months, bio: pr.bio, status: x.status } }) },
  hire(a) { const ap = DB.applications.find(x => x.id === a.p_app), po = DB.job_posts.find(p => p.id === ap.post_id); if (!canManage(po.store_id)) throw { message: '권한이 없어요' }; if (ap.status !== 'applied') throw { message: '이미 처리된 지원이에요' }; if (po.kind === 'urgent') { const sl = DB.job_slots.filter(s => s.post_id === po.id && s.status === 'OPEN').sort((a, b) => a.idx - b.idx)[0]; if (!sl) throw { message: '남은 자리가 없어요' }; sl.status = 'MATCHED'; sl.dealer_id = ap.user_id } ap.status = 'hired'; noti(ap.user_id, '채용됐어요! 지원권 1장이 사용됐어요') },
  cancel_hire(a) { const ap = DB.applications.find(x => x.id === a.p_app); ap.status = 'cancelled'; DB.job_slots.filter(s => s.post_id === ap.post_id && s.dealer_id === ap.user_id && s.status === 'MATCHED').forEach(s => { s.status = 'OPEN'; s.dealer_id = null }); DB.ticket_ledger.push({ user_id: ap.user_id, delta: 1, reason: 'refund' }); noti(ap.user_id, '매장이 채용을 취소해 지원권 1장을 돌려드렸어요') },
  get_contact(a) { const ap = DB.applications.find(x => x.id === a.p_app); return ap.status === 'hired' ? DB.profiles.find(p => p.id === ap.user_id).phone : null },
  join_list(a) { if (!canManage(a.p_store)) return []; return DB.join_requests.filter(r => r.store_id === a.p_store && r.status === 'pending').map(r => { const p = DB.profiles.find(p => p.id === r.user_id); return { req_id: r.id, user_id: r.user_id, name: p.name, phone: p.phone, career_months: p.career_months, bio: p.bio, created_at: r.created_at } }) },
  request_join(a) { const s = DB.stores.find(s => s.join_code.toUpperCase() === a.p_code.trim().toUpperCase()); if (!s) throw { message: '코드를 다시 확인해 주세요' }; DB.join_requests.push({ id: uid(), store_id: s.id, user_id: me(), status: 'pending', created_at: now() }); managers(s.id).forEach(u => noti(u, '새 소속 신청이 있어요')); return s.name },
  approve_join(a) { const r = DB.join_requests.find(x => x.id === a.p_req), s = DB.stores.find(x => x.id === r.store_id), pr = DB.profiles.find(p => p.id === r.user_id); let m; if (a.p_member) { m = DB.members.find(x => x.id === a.p_member); m.user_id = r.user_id } else { m = { id: uid(), company_id: s.company_id, store_id: s.id, user_id: r.user_id, role: 'staff', nick: pr.name, job_role: a.p_role, contract: a.p_contract, hourly_rate: a.p_rate, night_pay: true, active: true, created_at: now() }; DB.members.push(m) } r.status = 'approved'; noti(r.user_id, s.name + ' 소속이 됐어요!'); return m.id },
  set_manager(a) { const m = DB.members.find(x => x.id === a.p_member); if (!DB.members.some(o => o.company_id === m.company_id && o.user_id === me() && o.role === 'owner')) throw { message: '대표만 할 수 있어요' }; if (a.p_on && !m.user_id) throw { message: '앱에 가입해 소속된 직원만 점장이 될 수 있어요' }; m.role = a.p_on ? 'manager' : 'staff' },
  add_store(a) { const own = DB.members.find(m => m.user_id === me() && m.role === 'owner'); if (!own) throw { message: '대표님만' }; const c = DB.companies.find(x => x.id === own.company_id); const id = uid(); DB.stores.push({ id, company_id: c.id, name: a.p_name, area: a.p_area || null, need_by_wd: [3, 4, 3, 4, 6, 7, 2], join_code: 'Y' + Math.random().toString(36).slice(2, 7).toUpperCase(), created_at: now(), holidays: [], fixed: {} }); return id; },
  post_open_free(a) { const p = DB.job_posts.find(x => x.id === a.p_post); if (!canManage(p.store_id)) throw { message: '권한이 없어요' }; if (p.status !== 'unpaid' || postFee(p.id) > 0) return false; p.status = 'open'; p.paid_amount = 0; return true; },
  set_holiday(a) { if (!canManage(a.p_store)) throw { message: '권한이 없어요' }; const st = DB.stores.find(s => s.id === a.p_store), h = (st.holidays || []).filter(x => x !== a.p_date); if (a.p_on) h.push(a.p_date); st.holidays = h.sort() },
  set_need(a) { if (!canManage(a.p_store)) throw { message: '권한이 없어요' }; DB.stores.find(s => s.id === a.p_store).need_by_wd = a.p_need },
  attend_code(a) { if (!canManage(a.p_store)) throw { message: '권한이 없어요' }; return [{ code: code(a.p_store), secs_left: 30 - Math.floor(Date.now() / 1000) % 30 }] },
  attend(a) { const m = DB.members.find(x => x.user_id === me() && x.store_id); if (!m || a.p_code !== code(m.store_id)) throw { message: '코드가 맞지 않아요' }; const last = DB.attendance.filter(x => x.member_id === m.id).sort((x, y) => x.at < y.at ? 1 : -1)[0]; const k = last?.kind === 'in' ? 'out' : 'in'; DB.attendance.push({ id: uid(), member_id: m.id, store_id: m.store_id, kind: k, at: new Date(Date.now() + DB.attendance.length).toISOString() }); return k },
  post_slots(a) { return DB.job_slots.filter(s => s.post_id === a.p_post).map(s => ({ slot_id: s.id, idx: s.idx, start_t: s.start_t, end_t: s.end_t, pay: s.pay, extra: s.extra, status: s.status, dealer_name: DB.profiles.find(p => p.id === s.dealer_id)?.name, done_at: s.done_at })) },
  slot_act(a) { const s = DB.job_slots.find(x => x.id === a.p_slot), po = DB.job_posts.find(p => p.id === s.post_id), mg = canManage(po.store_id), v = a.p_act;
    if (v === 'start' && mg && s.status === 'MATCHED') s.status = 'WORKING';
    else if (v === 'noshow' && mg && s.status === 'MATCHED') { s.status = 'OPEN'; s.dealer_id = null }
    else if (v === 'extra' && mg && s.status === 'WORKING') s.extra += Math.round(s.pay / 5);
    else if (v === 'done' && s.dealer_id === me() && s.status === 'WORKING') { s.status = 'DONE'; s.done_at = now() }
    else if (v === 'ok' && mg && s.status === 'DONE') { const g = s.pay + s.extra, it = Math.floor(g * .03 / 10) * 10, t = it + Math.floor(it * .1 / 10) * 10; s.status = 'PAID'; s.result = { gross: g, tax: t, net: g - t }; DB.wallet_ledger.push({ user_id: s.dealer_id, amount: g - t, available_at: new Date(Date.now() + 5 * 36e5).toISOString() }) }
    else if (v === 'dispute' && mg && s.status === 'DONE') s.status = 'DISPUTED';
    else throw { message: '지금은 할 수 없는 동작이에요' } },
  my_slots() { return DB.job_slots.filter(s => s.dealer_id === me()).map(s => { const p = DB.job_posts.find(p => p.id === s.post_id); return { slot_id: s.id, status: s.status, start_t: s.start_t, end_t: s.end_t, pay: s.pay, extra: s.extra, result: s.result, title: p.title, store_name: DB.stores.find(x => x.id === p.store_id).name } }) },
  dealer_rep(a) { const done = DB.job_slots.filter(j => j.dealer_id === a.u && ['DONE', 'PAID'].includes(j.status)); const st = new Set(done.map(j => DB.job_posts.find(p => p.id === j.post_id)?.store_id)); return { done: done.length, stores: st.size, recall_pct: st.size ? 0 : null, noshow: 0, edu: DB.quiz_results.filter(q => q.user_id === a.u && q.passed).length, career: DB.profiles.find(p => p.id === a.u)?.career_months || 0 }; },
  my_wallet() { const L = DB.wallet_ledger.filter(x => x.user_id === me()); return [{ balance: L.reduce((a, x) => a + x.amount, 0), available: L.filter(x => x.available_at <= now()).reduce((a, x) => a + x.amount, 0) }] },



  pay_start(a) { const k = a.p_kind, g = a.p_arg || {}; let amt, nm, comp = null; const own = DB.members.find(m => m.user_id === me() && m.role === 'owner');
    if (k === 'tickets') { amt = [0, 5500, 24900, 44000][g.pack]; nm = '지원권'; } else if (k === 'pro') { amt = 9900; nm = 'PRO'; }
    else if (k === 'store') { if (!own) throw { message: '대표님만 결제할 수 있어요' }; comp = own.company_id; amt = 35000; nm = '매장 추가'; }
    else if (k === 'academy' || k === 'plan') { if (!own) throw { message: '대표님만 결제할 수 있어요' }; comp = own.company_id; amt = k === 'academy' ? 159000 : (g.plan === 'basic' ? 25000 : 35000); nm = k === 'academy' ? '+EV 딜러 교육 (매장 패키지)' : '+EV 프로 요금제 30일'; }
    else if (k === 'diag') { if (!own) throw { message: '대표님만 결제할 수 있어요' }; comp = own.company_id; amt = 10000; nm = '+EV 주변 매장 비교 진단 (30일)'; }
    else if (k === 'franchise') { const f = DB.franchise_postings.find(x => x.id === g.post); if (!f || f.owner_user !== me()) throw { message: '내 가맹 공고만' }; amt = 300000; nm = '가맹 모집 공고 30일: ' + f.brand; }
    else if (k === 'fr_bill') { const b = DB.payments.find(x => x.order_id === g.order && x.user_id === me() && x.status === 'due'); if (!b) throw { message: '청구서 없음' }; b.status = 'ready'; return [{ order_id: b.order_id, amount: b.amount, order_name: b.order_name }]; }
    else if (k === 'used_boost') { const u = DB.used_items.find(x => x.id === g.item); if (!u || u.seller !== me()) throw { message: '내 판매 글만' }; amt = g.type === 'urgent' ? 9900 : 4900; nm = g.type === 'urgent' ? '급매' : '상단 노출'; }
    else if (k === 'post_extra') { const p = DB.job_posts.find(x => x.id === g.post); if (!canManage(p.store_id)) throw { message: '권한이 없어요' }; amt = extraFee(p, g); nm = '공고 연장·옵션: ' + p.title; }
    else if (k === 'post') { const p = DB.job_posts.find(x => x.id === g.post); if (!canManage(p.store_id)) throw { message: '권한이 없어요' }; if (p.status !== 'unpaid') throw { message: '이미 결제된 공고예요' }; amt = postFee(p.id); nm = p.title; }
    const order_id = 'EV' + uid(); DB.payments.push({ order_id, user_id: me(), company_id: comp, kind: k, arg: g, amount: amt, order_name: nm, status: 'ready', refund_due: 0, refunded: 0, created_at: now() }); return [{ order_id, amount: amt, order_name: nm }]; },
  hq_verify(a) { if (!DB.profiles.find(p => p.id === me())?.is_hq) throw { message: '운영사만' }; DB.companies.find(c => c.id === a.p_company).biz_verified = true; },
  my_academy() { return DB.members.some(m => m.user_id === me() && m.active !== false && DB.companies.find(c => c.id === m.company_id)?.academy_at); },
  buy_academy() { const o = DB.members.find(m => m.user_id === me() && m.role === 'owner'); if (!o) throw { message: '대표님만' }; const c = DB.companies.find(c => c.id === o.company_id); if (c.academy_at) throw { message: '이미 이용 중' }; c.academy_at = now(); DB.purchases.push({ company_id: c.id, kind: 'academy', qty: 1, amount: 159000, status: 'beta' }); DB.members.filter(m => m.company_id === c.id && m.user_id && m.role !== 'owner').forEach(m => noti(m.user_id, '매장에서 딜러 교육을 열었어요')); },
  ask_owner(a) { if (!canManage(a.p_store)) throw { message: '권한이 없어요' }; const s = DB.stores.find(x => x.id === a.p_store); DB.members.filter(m => m.company_id === s.company_id && m.role === 'owner' && m.user_id).forEach(m => noti(m.user_id, '요청했어요: ' + a.p_what)); },
  lesson_done(a) { if (!RPC.my_academy()) throw { message: '매장에서 교육을 열어야' }; if (!DB.lesson_progress.some(x => x.user_id === me() && x.lesson === a.p_lesson)) DB.lesson_progress.push({ user_id: me(), lesson: a.p_lesson }); },
  submit_quiz(a) { if (!RPC.my_academy()) throw { message: '매장에서 교육을 열어야' }; const m = DB.members.find(x => x.user_id === me()), cq = DB.company_quiz.find(x => x.company_id === m.company_id), items = cq?.items?.length ? cq.items : [0, 1, 2, 2, 0].map(a => ({ type: 'mc', a })), nz = t => String(t || '').toLowerCase().replace(/\s/g, '');
    const s = items.filter((it, i) => (it.type || 'mc') === 'sa' ? nz(a.p_answers[i]) && String(it.a).split(',').map(nz).includes(nz(a.p_answers[i])) : +a.p_answers[i] === +it.a).length, ok = s >= Math.ceil(items.length * .8); DB.quiz_results.push({ user_id: me(), score: s, passed: ok, total: items.length, created_at: now() }); DB.members.filter(x => x.company_id === m.company_id && x.user_id && ['owner', 'manager'].includes(x.role)).forEach(x => noti(x.user_id, `시험 ${s}/${items.length}`)); return { score: s, passed: ok, total: items.length }; },
  fr_hit(a) { DB.franchise_events.push({ posting_id: a.p_post, kind: a.p_kind, created_at: now() }); },
  fr_dash(a) { const m0 = new Date().toISOString().slice(0, 7), ev = k => DB.franchise_events.filter(e => e.posting_id === a.p_post && e.kind === k && e.created_at.slice(0, 7) === m0).length, L = DB.franchise_leads.filter(l => l.posting_id === a.p_post && l.is_qualified && l.connected_at.slice(0, 7) === m0); return { views: ev('view'), details: ev('detail'), clicks: ev('click'), leads: L.length, cost: L.reduce((x, l) => x + l.charge_amount, 0), limited: false }; },
  set_franchise_perm(a) { if (!DB.profiles.find(p => p.id === me())?.is_hq) throw { message: '운영사만' }; DB.profiles.find(p => p.id === a.p_user).can_post_franchise = a.p_on; },
  fr_log_call(a) { const p = DB.franchise_postings.find(x => (x.tracking_number || '').replace(/-/g, '') === String(a.p_tracking).replace(/-/g, '')); if (!p) throw { message: '추적번호에 맞는 공고가 없어요' }; const h = 'h' + [...(String(a.p_caller).replace(/\D/g, '') + p.id)].reduce((x, ch) => (x * 31 + ch.charCodeAt(0)) >>> 0, 7).toString(16); let st = 'qualified', ok = false, amt = 0;
    if (a.p_seconds < 30) st = 'short'; else if (DB.franchise_leads.some(l => l.posting_id === p.id && l.caller_hash === h && l.is_qualified && new Date(l.connected_at) > new Date(a.p_connected_at) - 30 * 864e5)) st = 'duplicate'; else { ok = true; amt = 50000; }
    DB.franchise_leads.push({ id: uid(), posting_id: p.id, caller_hash: h, caller_tail: String(a.p_caller).replace(/\D/g, '').slice(-4), connected_at: a.p_connected_at, duration_seconds: a.p_seconds, is_qualified: ok, charge_amount: amt, status: st, created_at: now() }); if (ok) noti(p.owner_user, '📞 가맹 상담 전화 유효 리드'); return { status: st, charge: amt, posting: p.id }; },
  fr_log_call_hq(a) { if (!DB.profiles.find(p => p.id === me())?.is_hq) throw { message: '운영사만' }; return RPC.fr_log_call(a); },
  fr_dispute(a) { const l = DB.franchise_leads.find(x => x.id === a.p_lead); if (!l || !l.is_qualified) throw { message: '이의제기할 수 없는 리드예요' }; l.status = 'disputed'; l.dispute_note = a.p_note; DB.profiles.filter(p => p.is_hq).forEach(p => noti(p.id, '가맹 리드 이의제기')); },
  fr_resolve(a) { if (!DB.profiles.find(p => p.id === me())?.is_hq) throw { message: '운영사만' }; const l = DB.franchise_leads.find(x => x.id === a.p_lead); l.is_qualified = a.p_valid; l.charge_amount = a.p_valid ? 50000 : 0; l.status = a.p_valid ? 'qualified' : 'invalid'; l.reason = a.p_reason; },
  fr_monthly_bill() { const d0 = new Date(new Date().getFullYear(), new Date().getMonth() - 1, 1), m0 = `${d0.getFullYear()}-${String(d0.getMonth() + 1).padStart(2, '0')}`, mk = t => { const d = new Date(t); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`; }; const by = {}; DB.franchise_leads.filter(l => l.is_qualified && !l.billed_month && l.status === 'qualified' && mk(l.connected_at) === m0).forEach(l => { (by[l.posting_id] = by[l.posting_id] || []).push(l); }); Object.entries(by).forEach(([pid, ls]) => { const p = DB.franchise_postings.find(x => x.id === pid); ls.forEach(l => l.billed_month = m0 + '-01'); DB.payments.push({ order_id: 'EVFR' + uid(), user_id: p.owner_user, kind: 'franchise_leads', arg: { post: pid, month: m0, n: ls.length }, amount: ls.reduce((a, l) => a + l.charge_amount, 0), order_name: `${p.brand} ${+m0.slice(5)}월 가맹 상담 리드 ${ls.length}건`, status: 'due', refund_due: 0, refunded: 0, created_at: now() }); }); },
  my_quiz() { const m = DB.members.find(x => x.user_id === me() && x.active !== false), cq = m && DB.company_quiz.find(x => x.company_id === m.company_id); return cq ? cq.items.map(x => ({ q: x.q, o: x.o || [], type: x.type || 'mc' })) : null; },
  pay_tax(a) { const r = DB.payments.find(x => x.order_id === a.p_order); r.tax_invoice = a.p_on; DB.companies.find(c => c.id === r.company_id).tax_auto = a.p_on; return a.p_on; },
  academy_board(a) { if (!canManage(a.p_store)) return []; return DB.members.filter(m => m.store_id === a.p_store && m.user_id && m.role !== 'owner').map(m => { const q = DB.quiz_results.filter(x => x.user_id === m.user_id).at(-1); return { nick: m.nick, done: DB.lesson_progress.filter(x => x.user_id === m.user_id).length, score: q?.score ?? null, passed: q?.passed ?? null }; }); },
  hq_today() { return { biz: DB.companies.filter(c => !c.biz_verified).length, inq: DB.inquiries.filter(i => !i.reply).length, disputes: 0, pay_fail: 0, fr_disputes: DB.franchise_leads.filter(l => l.status === 'disputed').length, withdrawals: DB.withdrawals.filter(w => w.status !== '송금 완료').length, trial_ending: 0, expired: DB.companies.filter(c => !compActive(c)).length }; },
  hq_revenue() { const done = DB.payments.filter(p => p.status === 'done'); return { by_kind: done.map(p => ({ month: (p.approved_at || now()).slice(0, 7), kind: p.kind === 'plan' ? 'subscription' : p.kind, amount: p.amount })), mrr: DB.companies.filter(c => c.plan === 'pro').length * 35000, plans: { trial: 1, pro: 1, expired: 0 }, activation: { signups: 2, activated: 1 }, dealer_activation: { signups: 2, activated: 1 }, retention: { d1: 0.5, d7: null, d30: null }, fake_door: DB.events.filter(e => e.name === 'ai_schedule_click').length }; },
  set_plan(a) { const o = DB.members.find(m => m.user_id === me() && m.role === 'owner'); if (!o) throw { message: '대표님만' }; DB.companies.find(c => c.id === o.company_id).plan = a.p_plan; DB.purchases.push({ kind: 'plan_' + a.p_plan, qty: 1, amount: a.p_plan === 'pro' ? 35000 : 25000 }); },
  buy_tickets(a) { const [n, p] = [[1, 5500], [5, 24900], [10, 44000]][a.p_pack - 1]; if (DB.purchases.filter(x => x.user_id === me() && x.kind === 'tickets').reduce((s, x) => s + x.qty, 0) + n > 20) throw { message: '베타 기간에는 20장까지' }; DB.purchases.push({ user_id: me(), kind: 'tickets', qty: n, amount: p, status: 'beta' }); DB.ticket_ledger.push({ user_id: me(), delta: n, reason: 'buy' }); return n; },
  buy_pro() { const p = DB.profiles.find(x => x.id === me()); p.pro_until = new Date(Math.max(Date.now(), +new Date(p.pro_until || 0)) + 30 * 864e5).toISOString(); DB.purchases.push({ user_id: me(), kind: 'dealer_pro', qty: 1, amount: 9900 }); DB.ticket_ledger.push({ user_id: me(), delta: 2, reason: 'pro' }); return p.pro_until; },
  withdraw(a) { const p = DB.profiles.find(x => x.id === me()); if (!p.bank_acct || !p.bank_holder) throw { message: '내 정보에서 계좌를 먼저 넣어주세요' }; const avail = DB.wallet_ledger.filter(x => x.user_id === me() && x.available_at <= now()).reduce((s, x) => s + x.amount, 0), fee = a.p_instant && !(p.pro_until && new Date(p.pro_until) > new Date()) ? 1500 : 0; if (avail - fee < 1000) throw { message: '출금할 수 있는 돈이 부족해요' }; DB.wallet_ledger.push({ user_id: me(), amount: -avail, kind: 'withdraw', available_at: now() }); DB.withdrawals.push({ id: uid(), user_id: me(), amount: avail - fee, fee, instant: a.p_instant, bank: p.bank_name + ' ' + p.bank_acct, status: '요청', created_at: now() }); DB.profiles.filter(x => x.is_hq).forEach(h => noti(h.id, '출금 요청')); return avail - fee; },
  set_layout(a) { if (!canManage(a.p_store)) throw { message: '권한이 없어요' }; DB.stores.find(s => s.id === a.p_store).layout = a.p_layout; },
  put_metrics(a) { if (!canManage(a.p_store)) throw { message: '권한이 없어요' }; const s = DB.stores.find(x => x.id === a.p_store), row = { store_id: a.p_store, month: a.p_month, ...a.p, pyeong: s.pyeong ?? null, tables: s.tables ?? null }; const i = DB.store_metrics.findIndex(x => x.store_id === a.p_store && x.month === a.p_month); i >= 0 ? DB.store_metrics[i] = row : DB.store_metrics.push(row); },
  bench(a) { if (!canManage(a.p_store)) throw { message: '권한이 없어요' };
    const plan = DB.companies.find(c => c.id === DB.stores.find(s => s.id === a.p_store).company_id).plan;
    const mine = DB.store_metrics.filter(x => x.store_id === a.p_store && x.days >= 7 && x.sales > 0).sort((x, y) => x.month < y.month ? 1 : -1)[0];
    if (!mine) return { ready: false, why: 'mine' };
    const peers = Array.from({ length: 14 }, (_, i) => { const sales = (40 + i * 3) * 1e6, py = 25 + i % 10, t = 5 + i % 5; return { sales, sales_act: sales * .83, profit: sales * (.2 + i % 4 * .03), labor: sales * (.24 + i % 5 * .02), subs: sales * .02, goods: sales * .07, elec: py * 12000, water: py * 2200, net: py * 4000, entries: t * 6 * 25, days: 25, pyeong: py, tables: t, wd: [.8, .85, .8, .95, 1.35, 1.55, .7].map(v => sales / 30 * v) }; });
    const G = [...peers, mine].map(r => ({ r, spy: r.pyeong ? r.sales / r.pyeong : null, lr: r.labor / r.sales * 100, gr: r.goods / r.sales * 100, sr: r.labor ? r.subs / r.labor * 100 : null, epy: r.elec && r.pyeong ? r.elec / r.pyeong : null, wpy: r.water && r.pyeong ? r.water / r.pyeong : null, npy: r.net && r.pyeong ? r.net / r.pyeong : null, ept: r.entries && r.tables ? r.entries / r.tables / r.days : null, ticket: r.entries ? r.sales_act / r.entries : null, pm: r.profit / r.sales * 100, fpy: r.pyeong && (r.elec + r.water + r.net) ? (r.elec + r.water + r.net) / r.pyeong : null }));
    const n = G.length, M = G.at(-1); const co = DB.companies.find(c => c.id === DB.stores.find(s => s.id === a.p_store).company_id); if (!compActive(co)) return { ready: true, locked: true, n, month: mine.month };
    const avg = k => { const v = G.map(x => x[k]).filter(x => x != null); return v.length ? v.reduce((a, b) => a + b, 0) / v.length : null; };
    const q = (k, p) => { const v = G.map(x => x[k] ?? x.r[k]).filter(x => x != null).sort((a, b) => a - b); return v[Math.floor((v.length - 1) * p)]; };
    const sc = (k, hi) => { const v = G.map(x => x[k]).filter(x => x != null); if (M[k] == null || v.length < 2) return null; return Math.round(100 * v.filter(x => hi ? x < M[k] : x > M[k]).length / (v.length - 1)); };
    return { ready: true, locked: false, n, month: mine.month, s_pct: Math.ceil(100 * (G.filter(x => x.r.sales > mine.sales).length + 1) / n), h_pct: Math.ceil(100 * (G.filter(x => x.r.profit > mine.profit).length + 1) / n),
      mine: { ...mine, ...Object.fromEntries(Object.entries(M).filter(([k]) => k !== 'r')) },
      avg: { sales: G.reduce((a, x) => a + x.r.sales, 0) / n, spy: avg('spy'), lr: avg('lr'), gr: avg('gr'), sr: avg('sr'), epy: avg('epy'), wpy: avg('wpy'), npy: avg('npy'), ept: avg('ept'), ticket: avg('ticket'), pm: avg('pm'), wd: [0, 1, 2, 3, 4, 5, 6].map(i => G.reduce((a, x) => a + (x.r.wd?.[i] || 0), 0) / n) },
      top25: { sales: q('sales', .75), spy: q('spy', .75), ept: q('ept', .75) }, cut: { 50: q('sales', .5), 25: q('sales', .75), 10: q('sales', .9), 5: q('sales', .95) },
      score: { s_sales: sc('spy', 1), s_profit: sc('pm', 1), s_labor: sc('lr', 0), s_fixed: sc('fpy', 0), s_util: sc('ept', 1) }, rates: { '딜러': 13200, '플로어': 11300 } };
  },
  store_rank(a) { return [{ sales_pct: 18, stores: 23 }] },
  hq_store_stats() { if (!DB.profiles.find(p => p.id === me())?.is_hq) return []; return DB.stores.map(s => { const c = DB.companies.find(c => c.id === s.company_id); return { company: c.name, brand: c.brand, store_id: s.id, store: s.name, area: s.area, verified: c.biz_verified, plan: c.plan, sales: DB.daily_reports.filter(r => r.store_id === s.id).reduce((a, r) => a + r.sales, 0), days: DB.daily_reports.filter(r => r.store_id === s.id).length, expenses: DB.expenses.filter(e => e.store_id === s.id).reduce((a, e) => a + e.amount, 0), staff: DB.members.filter(m => m.store_id === s.id).length } }) }
};
export function createClient() {
  return {
    auth: {
      onAuthStateChange(cb) { cbs.push(cb); setTimeout(() => cb('INIT', user ? { user } : null), 0) },
      async signUp({ email, options }) { if (window.__USERS[email]) return { data: {}, error: { message: 'User already registered' } }; user = { id: uid(), email }; window.__USERS[email] = user; DB.profiles.push({ id: user.id, name: options.data.name, is_hq: email.startsWith('hq@') }); cbs.forEach(c => c('SIGNED_IN', { user })); return { data: { session: {} }, error: null } },
      async signInWithPassword({ email }) { const u = window.__USERS[email]; if (!u) return { error: { message: 'Invalid login' } }; user = u; cbs.forEach(c => c('SIGNED_IN', { user })); return { error: null } },
      async signOut() { user = null; cbs.forEach(c => c('SIGNED_OUT', null)) }
    },
    storage: { from: b => ({ upload: async (path, blob) => { DB.__storage.push({ b, path, size: blob?.size }); return { data: { path }, error: null }; }, getPublicUrl: path => ({ data: { publicUrl: `https://hkcmsjwuwopxritafreg.supabase.co/storage/v1/object/public/${b}/${path}` } }) }) },
    functions: { invoke: async (n, { body }) => { try { if (n === 'pay-confirm') { const r = DB.payments.find(x => x.order_id === body.orderId); if (!r || r.user_id !== me()) throw { message: '주문을 찾을 수 없어요' }; if (+body.amount !== r.amount) throw { message: '결제 금액이 주문과 달라요' }; return { data: fulfill(body.orderId), error: null }; }
      if (n === 'sched-auto') { const st = DB.members.filter(m => m.store_id === body.store_id && m.active !== false && m.role !== 'owner'), short = []; for (const [d, n] of Object.entries(body.need)) { const w = (new Date(d + 'T00:00:00Z').getUTCDay() + 6) % 7, have = Math.min(n, st.filter(m => DB.shift_templates.some(t => t.member_id === m.id && t.weekday === w)).length); if (have < n) short.push({ d, need: n, have }); } RPC.sched_step({ p_store: body.store_id, p_month: body.month, p_status: 'draft' }); DB.sched_rounds.find(x => x.store_id === body.store_id && x.month === body.month).short = short; return { data: { ok: true, short, ai: 'none' }, error: null }; }
      if (n === 'pay-refund') { const r = DB.payments.find(x => x.order_id === body.orderId), due = r.refund_due - r.refunded; r.refunded += due; return { data: { ok: true, refunded: due }, error: null }; } } catch (e) { return { data: e, error: e }; } } },
    from: t => builder(t),
    rpc: (n, a) => ({ then(res) { try { if (!RPC[n]) { res({ data: null, error: null }); return; } res({ data: RPC[n](a || {}) ?? null, error: null }) } catch (e) { res({ data: null, error: e }) } } })
  }
}
